
# Site settings
title: Tieming Wu
name: Tieming Wu
subtitle:  Ph.D. student
email: wutiemingzuihaole@hrbeu.edu.cn
description: >
   Ph.D. student
baseurl: ""
url: "https://wutieming.github.io/"
github_username:  wutieming
disqus_baseurl: "https://wutieming.github.io/"
disqus_shortname: https-wutieming-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Tieming Wu"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: wutieming
    url: https://github.com/wutieming
    desc: Fork me on GitHub
    share: false
